<?php
$today = date("Ymd");
$yesterday = date("Ymd",strtotime('-1 day'));

// cronは、1日1回くらい巡回すればいいかな

// 巡回するサイトのURLを指定する
$url = "https://subaru-kikan-job.net/jobfind-pc/";
// 巡回したサイトのHTMLファイルを保存する
$data = file_get_contents($url);

// 保存するディレクトリのパス
$svdirpass = "./download/{$today}";
// 保存するファイル名
$svfilename = "saved.html";

// ディレクトリの作成
if(file_exists($svdirpass) == false) {
    mkdir($svdirpass,0777,true);
}

// 日付ディレクトリ内にファイルが存在しないことを確認
if(file_exists($svdirpass."/".$svfilename) == false) {
    echo "ファイルを保存します\n";
    // ファイルの保存
    file_put_contents($svdirpass."/".$svfilename,$data);
} else {
    echo "保存失敗（ファイルが存在しています。）\n";
}

// 今日のファイルサイズ
$filesize_today = filesize($svdirpass."/".$svfilename);
echo "今日のファイルサイズ：".$filesize_today."\n";

// 巡回したサイトのHTMLファイルのファイルサイズを前回に保存したものと比較する
$yesterdaysvdirpass = "./download/{$yesterday}";
// 昨日のファイルサイズ
$filesize_yesterday = filesize($yesterdaysvdirpass."/".$svfilename);

if (file_exists($yesterdaysvdirpass) == true) {
    echo "昨日のファイルのサイズ：".$filesize_yesterday."\n";
}

// ファイルサイズが違かったら、SSを撮影＆Slackに通知をする
if ($filesize_today !== $filesize_yesterday) {
    echo "ページに変化があります。\n";
    // APIコール
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://hooks.slack.com/services/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');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"text\":\"ウェブサイトに変更があります！\"}");
    curl_setopt($ch, CURLOPT_POST, 1);

    $headers = array();
    $headers[] = 'Content-Type: application/json';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);

    
}

// api
function screenshotlayer($url) {

    // set access key
    $access_key = "c9810d7fb7b6973980df6c6436b9793e";
    
    // set secret keyword (defined in account dashboard)
    $secret_keyword = "takuyakawai123$%^7789";
  
    // encode target URL
    $params['url'] = urlencode($url);
    // $params += $args;
  
    // create the query string based on the options
    foreach($params as $key => $value) { $parts[] = "$key=$value"; }
  
    // compile query string
    $query = implode("&", $parts);
  
    // generate secret key from target URL and secret keyword
    $secret_key = md5($url . $secret_keyword);

    return "https://api.screenshotlayer.com/api/capture?access_key=$access_key&secret_key=$secret_key&$query";
  
  }
  
  // set optional parameters (leave blank if unused)
  $params['fullpage']  = '';    
  $params['width'] = '';      
  $params['viewport']  = '';  
  $params['format'] = '';      
  $params['css_url'] = '';      
  $params['delay'] = '';      
  $params['ttl'] = '';  
  $params['force']     = '';     
  $params['placeholder'] = '';      
  $params['user_agent'] = '';      
  $params['accept_lang'] = '';      
  $params['export'] = '';      
  
  // capture
  //  $call = screenshotlayer("google.com", $params);  